using System.ComponentModel.DataAnnotations;
namespace ConfidraApi.Common.Models;
public sealed class CareConsent { public int Id { get; set; } public int UserId { get; set; } [MaxLength(30)] public string Purpose { get; set; } = ""; [MaxLength(30)] public string Version { get; set; } = "2026-09-30"; public DateTime GrantedUtc { get; set; } public DateTime? WithdrawnUtc { get; set; } }
public sealed class PatientIntake { [Key] public int UserId { get; set; } [MaxLength(100)] public string City { get; set; } = ""; [MaxLength(40)] public string DiabetesType { get; set; } = ""; [MaxLength(100)] public string Duration { get; set; } = ""; [MaxLength(2000)] public string Medicines { get; set; } = ""; [MaxLength(2000)] public string OtherConditions { get; set; } = ""; public DateTime UpdatedUtc { get; set; } }
public sealed class DailyLog { public int Id { get; set; } public int UserId { get; set; } public DateOnly Date { get; set; } public decimal? FastingGlucose { get; set; } public int? Systolic { get; set; } public int? Diastolic { get; set; } public decimal? WeightKg { get; set; } public int? Energy { get; set; } public DateTime UpdatedUtc { get; set; } }
public sealed class CareAssignment { public int Id { get; set; } public int PatientId { get; set; } public int StaffId { get; set; } }
public sealed class ClinicalReview { public int Id { get; set; } public int PatientId { get; set; } public int PhysicianId { get; set; } public int Day { get; set; } public decimal? Fbs { get; set; } public decimal? Ppbs { get; set; } public decimal? HbA1c { get; set; } [MaxLength(4000)] public string Interpretation { get; set; } = ""; public DateTime RecordedUtc { get; set; } }
public sealed class Referral { public int Id { get; set; } public int ReferrerId { get; set; } [MaxLength(150)] public string PatientName { get; set; } = ""; [MaxLength(30)] public string Phone { get; set; } = ""; public DateTime ConsentConfirmedUtc { get; set; } [MaxLength(30)] public string Status { get; set; } = "Received"; public DateTime CreatedUtc { get; set; } }
public sealed class AuditEvent { public long Id { get; set; } public int ActorId { get; set; } public int? SubjectId { get; set; } [MaxLength(60)] public string Action { get; set; } = ""; public DateTime CreatedUtc { get; set; } }
public sealed class PaymentRecord { [Key, MaxLength(80)] public string OrderId { get; set; } = ""; public int UserId { get; set; } [MaxLength(40)] public string ProgrammeId { get; set; } = ""; public int AmountPaise { get; set; } [MaxLength(80)] public string? PaymentId { get; set; } [MaxLength(25)] public string Status { get; set; } = "Created"; public DateTime CreatedUtc { get; set; } }
public sealed class ProviderEvent { [Key, MaxLength(150)] public string Id { get; set; } = ""; public DateTime ProcessedUtc { get; set; } }
public sealed record IntakeInput([Required, MaxLength(100)] string City, [Required, RegularExpression("^(Pre-diabetes|Type 1|Type 2|Gestational|Not sure)$")] string DiabetesType, [Required, MaxLength(100)] string Duration, [MaxLength(2000)] string Medicines, [MaxLength(2000)] string OtherConditions);
public sealed record LogInput(DateOnly Date, [Range(1,1500)] decimal? FastingGlucose, [Range(20,350)] int? Systolic, [Range(10,250)] int? Diastolic, [Range(1,500)] decimal? WeightKg, [Range(1,10)] int? Energy);
public sealed record ConsentInput([Required, RegularExpression("^(HealthData|Teleconsultation|ClinicalSharing)$")] string Purpose, bool Granted);
public sealed record ReferralInput([Required, MaxLength(150)] string PatientName, [Required, RegularExpression(@"^\+?[0-9 \-]{10,20}$")] string Phone, bool PatientConsent);
public sealed record ReviewInput([Range(0,90)] int Day, [Range(1,1500)] decimal? Fbs, [Range(1,1500)] decimal? Ppbs, [Range(1,30)] decimal? HbA1c, [Required, MaxLength(4000)] string Interpretation);
